---
platform: linux
inputs:
- name: git-repo
- name: release-notes-repo
- name: version
outputs:
- name: generated-release-notes
params:
  GITHUB_ORGANIZATION:
  GITHUB_REPO:
  GITHUB_USERNAME:
  GITHUB_PASSWORD:
  RELEASE_TYPE:
run:
  path: git-repo/ci/scripts/generate-release-notes.sh
